name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/hon
          zip -r haier_hon.zip ./ -x '__pycache__/*'

      - name: Attach zip to release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/custom_components/hon/haier_hon.zip
